/*
 * Automatically generated by SP Control panel
 * CRUD service.js for including the various packages required.
 */

var simpleportal = require("simpleportal");

var arbeitsmappeService = new simpleportal.Service.CRUDService({
	"collection":"arbeitsmappe", 
	"name":"arbeitsmappe", 
	modify:true
	,"primaryKey":"_id"
	,"primaryKeyFields":"szenario"
	,model:{
		"szenario":"",
		"typ":"",
		"beschreibung":[""],
		"ressourcen":{},
		"bewertung":{},
		"risikobewertung":""
	},"validation":{
	},"configuration":{
		modelsettings:{
			typ:{ajax:true, url:'search', displayoptions:{datakey:'typ', datadisplay:'typ', custom:true}},
			beschreibung:{type:'textarea'},
			"ressourcen":{
				model:{
					hr:"",
					eur:"",
					time:''
				}
			},"bewertung":{
				model:{
					pro:[""],
					contra:[""]
				}
			}
		}
	}
});

/*
 * Exporting the Sponsor service.
 */
module.exports = arbeitsmappeService;