/*
 * Automatically generated by SP Control panel
 * CRUD service.js for including the various packages required.
 */

var simpleportal = require("simpleportal");

var itemphaseService = new simpleportal.Service.CRUDService({
	"collection":"itemphase", 
	"name":"itemphase", modify:true
	,"title":"Itemphase"
	
	
	,"primaryKeyFields":"title"
	
	,model:{"title":"","description":""
	},"validation":{
		"title":"required",
	}
});

/*
 * Exporting the Sponsor service.
 */
module.exports = itemphaseService;