/*
 * Automatically generated by SP Control panel
 * CRUD service.js for including the various packages required.
 */

var simpleportal = require("simpleportal");

var itemcategoryService = new simpleportal.Service.CRUDService({
	"collection":"itemcategory", 
	"name":"itemcategory", modify:true
	,"title":"Itemcategory"
	,"primaryKeyFields":"title",
	defaultsort:{sort:[['priority', 1],['title', 1]]}
	,model:{"title":"","description":"", "priority":0, "depends":"", "status":"default"
	},"validation":{
		"title":"required",
	}, configuration:{
		modelsettings:{
			depends:{url:"search", displayoptions:{datadisplay:"title"}},
			description:{type:'textarea'},
			status:{url:"status"}
		}
	}
});

/*
 * Exporting the Sponsor service.
 */
module.exports = itemcategoryService;