/*
 * Automatically generated by SP Control panel
 * CRUD service.js for including the various packages required.
 */

var simpleportal = require("simpleportal");

var projectitemService = new simpleportal.Service.CRUDService({
	"collection":"projectitem", 
	"name":"projectitem", modify:true
	,"title":"Projectitem"
	,"primaryKeyFields":["project", "itemtitle"],
	defaultsort:{sort:[['project', 1], ['priority', 1],['itemtitle', 1]]}, 	
	model:{
		"project":"",
		"itemtitle":"",
		"itemcategory":"",
		"priority":0,
		"depends":[''],
		"itemphase":"",
		"itemdescription":"",
		"resourcerole":"",
		"timeinhours":0,
		subitems:[],
		status:""
//		,"costinhours":0
	},"validation":{
		"project":"required",
		"itemtitle":"required",
		"timeinhours":"number",
	}, configuration:{
		modelsettings:{
			priority:{type:'number'},
			itemphase:{url:"/api/itemphase", displayoptions:{datadisplay:'title', dataid:'id'}},
			itemcategory:{url:"/api/itemcategory", displayoptions:{datadisplay:'title', dataid:'id'}},
			depends:{url:"search", displayoptions:{datadisplay:"itemtitle", multiple:true}},
			itemdescription:{type:'textarea'},
			resourcerole:{url:"/api/resourcerole", displayoptions:{datadisplay:'title', dataid:'id'}, inherit:['costinhours']},
			project:{url:"/api/project", displayoptions:{datadisplay:'title', dataid:'id'}},
			subitems:{
				model:{
					"priority":0,
					"itemtitle":"",
					"itemdescription":"",
					"resourcerole":"",
					"timeinhours":0
				},
				modelsettings:{
					itemdescription:{type:'textarea'},
					resourcerole:{url:"/api/resourcerole", displayoptions:{datadisplay:'title', dataid:'id'}, inherit:['costinhours']},
				}, validation:{
					itemtitle:"required"
				}
			},
			status:{url:'status', displayoptions:{plugin:"radio"}}
		}
	}, dataformat : function(object, request) {
		if((!object.timeinhours || object.timeinhours == 0) && object.subitems && object.subitems.length > 0){
			object.timeinhours=0;
			for(var index in object.subitems){
				var subitem = object.subitems[index];
				if(subitem&& subitem.timeinhours){
					object.timeinhours += Number(subitem.timeinhours);
				}
			}
		}
		
		return object;
	}
});

projectitemService.beforeSave = function(projectitem, callback, options){
	if(projectitem && projectitem.resourcerole){
		simpleportal.serviceloader.resourcerole.details(projectitem.resourcerole, function(error, resourcerole){
			if(resourcerole && resourcerole.costinhours)
				projectitem.costinhours=Number(resourcerole.costinhours);
			
			callback(null, projectitem);
		});
	}
}

/*
 * Exporting the Sponsor service.
 */
module.exports = projectitemService;