/*
 * Automatically generated by SP Control panel
 * CRUD service.js for including the various packages required.
 */

var simpleportal = require("simpleportal");

var resourceroleService = new simpleportal.Service.CRUDService({
	"collection":"resourcerole", 
	"name":"resourcerole", modify:true
	,"title":"Resourcerole"
	,defaultsort:{sort:[['title', 1]]} 
	,"primaryKeyFields":"title"
	
	,model:{"title":"","costinhours":0
	},"validation":{
		"title":"required",
		"costinhours":"float",
	}
});

/*
 * Exporting the Sponsor service.
 */
module.exports = resourceroleService;